import { z } from 'zod';

/**
 * Robust password policy (RF-2.6.2): at least 12 characters mixing lowercase,
 * uppercase, digits and a special character. Applied to every user-CHOSEN
 * password (coordinator sign-up, change and reset) so a strong one can't later
 * be downgraded. Autogenerated psychologist passwords already exceed this.
 */
export const strongPasswordSchema = z
  .string()
  .min(12, 'La contraseña debe tener al menos 12 caracteres')
  .regex(/[a-z]/, 'Debe incluir una letra minúscula')
  .regex(/[A-Z]/, 'Debe incluir una letra mayúscula')
  .regex(/[0-9]/, 'Debe incluir un número')
  .regex(/[^A-Za-z0-9]/, 'Debe incluir un carácter especial');

/**
 * Venezuelan MOBILE number: a carrier prefix (0412/0414/0416/0424/0426) followed
 * by exactly 7 digits, optionally written with the +58 country code instead of
 * the leading 0. Tolerant of spaces, dashes, dots and parentheses. Landlines are
 * rejected (the app reaches people by call/WhatsApp). Source of truth mirrored by
 * the web `isValidVePhone`. NOT used for crisis-line numbers (short/service codes).
 */
const VE_PHONE_RE = /^(\+?58|0)?(412|414|416|424|426)\d{7}$/;
export const venezuelanPhoneSchema = z
  .string()
  .trim()
  .refine((v) => VE_PHONE_RE.test(v.replace(/[\s().-]/g, '')), {
    message: 'Teléfono venezolano inválido (ej. 0414-1234567)',
  });

/**
 * Identity document number: a V/E cédula is up to 8 digits; a passport (P) is
 * alphanumeric (5–20). Used via a refine so the rule can see `tipo_documento`.
 */
export function isValidDocumentNumber(tipo: 'V' | 'E' | 'P', numero: string): boolean {
  const value = numero.trim();
  return tipo === 'P' ? /^[A-Za-z0-9]{5,20}$/.test(value) : /^\d{1,8}$/.test(value);
}

/** Request validation schemas for the intake endpoints (Block 3). */

export const triageInitialSchema = z.object({
  respuesta_likert: z.number().int().min(1).max(5),
});

export const redBranchSchema = z.object({
  sub_canal: z.enum(['llamar', 'recibir-llamada', 'whatsapp-silencioso']),
  nombre: z.string().min(1).optional(),
  contacto: venezuelanPhoneSchema.optional(),
  edad: z.number().int().min(0).max(120).optional(),
});

/** Recent habit changes (green-branch screen 5, RF-1.3 pantalla 5). */
export const habitChangeEnum = z.enum([
  'alimentacion',
  'concentracion',
  'aseo',
  'relaciones',
  'sueno',
]);

export const greenBranchSchema = z.object({
  nombre: z.string().min(1).optional(),
  contacto: venezuelanPhoneSchema,
  tipo_solicitante: z.enum(['victima', 'familiar', 'voluntario']).optional(),
  // Free-form zone kept for compatibility; location screen sends estado + ciudad.
  zona: z.string().min(1).optional(),
  estado: z.string().min(1).optional(),
  ciudad: z.string().min(1).optional(),
  modalidad: z.enum(['presencial', 'distancia']).optional(),
  // Preferred contact channel (RF-1.3 screen 2): WhatsApp or phone call.
  metodo_contacto: z.enum(['whatsapp', 'llamada']).optional(),
  edad: z.number().int().min(0).max(120).optional(),
  tags: z.array(z.string().min(1)).default([]),
  cambio_habitos: z.array(habitChangeEnum).default([]),
});

/** Complete applicant form vocab (RF-2.1.2). */
export const documentTypeEnum = z.enum(['V', 'E', 'P']);
export const modalidadEnum = z.enum(['presencial', 'distancia']);
export const diaSemanaEnum = z.enum([
  'lunes',
  'martes',
  'miercoles',
  'jueves',
  'viernes',
  'sabado',
  'domingo',
]);
export const bloqueHorarioEnum = z.enum(['manana', 'tarde', 'noche']);
export const availabilitySlotSchema = z.object({
  dia: diaSemanaEnum,
  bloque: bloqueHorarioEnum,
});

export const registerVolunteerSchema = z
  .object({
    nombre: z.string().min(1),
    // Personal identity document (RF-2.1.2): type + number, separate from the FPV.
    tipo_documento: documentTypeEnum,
    numero_documento: z.string().min(1),
    // FPV professional registration number (persisted as professional_id).
    numero_fpv: z.string().min(1),
    email: z.string().email(),
    // Contact phone (RF-2.1.2) — required so a coordinator can reach the volunteer.
    telefono: venezuelanPhoneSchema,
    universidad: z.string().min(1),
    anio_egreso: z
      .number()
      .int()
      .min(1950)
      .max(new Date().getFullYear()),
    colegio: z.string().min(1),
    especialidad: z.string().min(1).optional(),
    modalidad: z.array(modalidadEnum).min(1),
    disponibilidad_horaria: z.array(availabilitySlotSchema).min(1),
    // PAP (Primeros Auxilios Psicológicos): trained yes/no + detail when yes.
    pap: z.boolean(),
    pap_detalle: z.string().min(1).optional(),
    // Informed consent (RF-2.1.1): mandatory. `z.literal(true)` makes a request
    // without acceptance fail validation, so registration is blocked server-side
    // regardless of the UI. The version is the wording the client displayed.
    consentimiento: z.literal(true),
    consentimiento_version: z.string().min(1),
  })
  .refine((v) => !v.pap || (v.pap_detalle !== undefined && v.pap_detalle.length > 0), {
    message: 'pap_detalle es obligatorio cuando pap es true',
    path: ['pap_detalle'],
  })
  .refine((v) => isValidDocumentNumber(v.tipo_documento, v.numero_documento), {
    message: 'Documento inválido: la cédula (V/E) debe tener hasta 8 dígitos',
    path: ['numero_documento'],
  });

export const loginSchema = z.object({
  email: z.string().email(),
  contrasena: z.string().min(1),
});

export const addNoteSchema = z.object({
  contenido: z.string().min(1),
  diagnostico: z.string().min(1).optional(),
  tept_diagnostico: z.boolean().optional(),
  crisis_psicotica_aguda: z.boolean().optional(),
});

export const caseClosureSchema = z.object({
  contacto: z.boolean(),
  motivo_no_contacto: z
    .enum(['abandono', 'problemas_conexion', 'solo_primer_contacto', 'solicitud_tercero'])
    .optional(),
  sexo: z.enum(['femenino', 'masculino', 'lgbtq', 'no_binario']).optional(),
  sintomas: z.array(z.string().min(1)).default([]),
  otro_sintoma: z.string().max(150).optional(),
  medio_contacto: z.enum(['celular', 'whatsapp', 'linea_fija']).optional(),
  tecnicas: z.array(z.string().min(1)).default([]),
  motivo_cierre: z.string().min(1).optional(),
  derivacion_tipo: z.enum(['urgente', 'seguimiento', 'ninguna']).optional(),
  derivacion_destino: z
    .enum(['psicologia', 'psiquiatria', 'ambos', 'medicina', 'proteccion_ninos', 'proteccion_mujer'])
    .optional(),
  horas: z.number().min(0).max(1000),
  comentario: z.string().max(1500).optional(),
});

const hour = z.number().int().min(0).max(26); // up to 26 to express ranges past midnight

export const crisisLineCreateSchema = z.object({
  nombre: z.string().min(1),
  telefono: z.string().min(1),
  cobertura: z.string().min(1).optional(),
  hora_inicio: hour.optional(),
  hora_fin: hour.optional(),
  // Days the line operates; omitted/undefined = every day.
  dias_semana: z.array(diaSemanaEnum).min(1).optional(),
  prioridad: z.number().int().optional(),
  activa: z.boolean().optional(),
});

export const crisisLineUpdateSchema = z
  .object({
    nombre: z.string().min(1),
    telefono: z.string().min(1),
    cobertura: z.string().min(1).nullable(),
    hora_inicio: hour.nullable(),
    hora_fin: hour.nullable(),
    // null clears back to "every day".
    dias_semana: z.array(diaSemanaEnum).min(1).nullable(),
    prioridad: z.number().int(),
    activa: z.boolean(),
  })
  .partial();

/** Confidential coordinator note about a volunteer (RF-2.4). */
export const volunteerNoteSchema = z.object({
  contenido: z.string().min(1).max(1500),
});

/** Coordinator manual reassignment of a case (RF-2.3). */
export const reassignCaseSchema = z.object({
  voluntario_id: z.string().min(1),
});

/** Coordinator administrative close of a case (RF-2.3). */
export const coordinatorCloseSchema = z.object({
  motivo: z.enum(['estancado', 'duplicado', 'resuelto_externamente', 'solicitud_tercero', 'otro']),
});

export const coordinatorInviteSchema = z.object({
  nombre: z.string().min(1),
  email: z.string().email(),
});

// Coordinator activation (RF-2.6 / #133): every coordinator is a registered
// psychologist first, so accepting an invitation only adds the coordinator role
// to the account that owns the invited email — the token alone is enough.
export const acceptInvitationSchema = z.object({
  token: z.string().min(1),
});

// Public preview of an invitation (token only) so onboarding can adapt the flow.
export const invitationInfoSchema = z.object({
  token: z.string().min(1),
});

export const auditQuerySchema = z.object({
  accion: z.string().min(1).optional(),
  registro: z.string().min(1).optional(),
  usuario: z.string().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(200).optional(),
  offset: z.coerce.number().int().min(0).optional(),
});

// Authenticated password change (RF-2.2.4): re-verify the current password and
// require a reasonable minimum length for the new one.
export const changePasswordSchema = z.object({
  contrasena_actual: z.string().min(1),
  contrasena_nueva: strongPasswordSchema,
});

// Public "forgot password" request (RF-2.2.4). Only the email is needed; the
// response is uniform whether or not an account exists (no enumeration).
export const forgotPasswordSchema = z.object({
  email: z.string().email(),
});

// Public reset redemption (RF-2.2.4): the single-use token plus the new password.
export const resetPasswordSchema = z.object({
  token: z.string().min(1),
  contrasena: strongPasswordSchema,
});

// Presence heartbeat / availability toggle (RF-2.5 / RF-4.3.1). `disponible`
// true refreshes the online TTL; false marks the volunteer offline immediately.
export const presenceSchema = z.object({
  disponible: z.boolean(),
});

// Admin-configurable assignment settings (RF-2.5 load balancing): the max active
// caseload a psychologist may hold before the balancer skips them for new cases.
export const assignmentSettingsSchema = z.object({
  max_active_caseload: z.number().int().min(1).max(100),
});

export type AddNoteBody = z.infer<typeof addNoteSchema>;
export type CaseClosureBody = z.infer<typeof caseClosureSchema>;
export type TriageInitialBody = z.infer<typeof triageInitialSchema>;
export type RedBranchBody = z.infer<typeof redBranchSchema>;
export type GreenBranchBody = z.infer<typeof greenBranchSchema>;
export type RegisterVolunteerBody = z.infer<typeof registerVolunteerSchema>;
export type LoginBody = z.infer<typeof loginSchema>;
export type CrisisLineCreateBody = z.infer<typeof crisisLineCreateSchema>;
export type CrisisLineUpdateBody = z.infer<typeof crisisLineUpdateSchema>;
export type VolunteerNoteBody = z.infer<typeof volunteerNoteSchema>;
export type ReassignCaseBody = z.infer<typeof reassignCaseSchema>;
export type CoordinatorCloseBody = z.infer<typeof coordinatorCloseSchema>;
export type CoordinatorInviteBody = z.infer<typeof coordinatorInviteSchema>;
export type AcceptInvitationBody = z.infer<typeof acceptInvitationSchema>;
export type InvitationInfoBody = z.infer<typeof invitationInfoSchema>;
export type ChangePasswordBody = z.infer<typeof changePasswordSchema>;
export type ForgotPasswordBody = z.infer<typeof forgotPasswordSchema>;
export type ResetPasswordBody = z.infer<typeof resetPasswordSchema>;
export type PresenceBody = z.infer<typeof presenceSchema>;
export type AssignmentSettingsBody = z.infer<typeof assignmentSettingsSchema>;
export type AuditQuery = z.infer<typeof auditQuerySchema>;
