import { ApiError } from '../../shared/errors/api-error';
import { generatePassword, hashPassword } from '../../shared/security/password';
import { logger } from '../../shared/logger';
import type { AuditLogRepository } from '../../domain/audit/audit';
import type { Volunteer, VolunteerRepository } from '../../domain/volunteer/volunteer';
import type { Notifier } from './ports';

export interface ManageVolunteerDeps {
  volunteers: VolunteerRepository;
  audit: AuditLogRepository;
  notifier: Notifier;
}

/** Who performed the action (coordinator or admin); recorded in the audit log. */
export interface Actor {
  id: string;
  role: string;
}

async function requireVolunteer(
  deps: ManageVolunteerDeps,
  volunteerId: string,
): Promise<Volunteer> {
  const volunteer = await deps.volunteers.findById(volunteerId);
  if (!volunteer) {
    throw new ApiError(404, 'NOT_FOUND', 'Volunteer not found');
  }
  return volunteer;
}

/**
 * A coordinator or admin resolves an exception: approve a pending volunteer
 * (RF-2.3). Because the password is autogenerated (RF-2.2.4) and a pending
 * volunteer never received one, approval reissues fresh credentials and emails
 * the welcome message so the account is usable — otherwise the volunteer would
 * be locked out.
 */
export async function approveVolunteer(
  volunteerId: string,
  actor: Actor,
  deps: ManageVolunteerDeps,
): Promise<void> {
  const volunteer = await requireVolunteer(deps, volunteerId);
  const temporaryPassword = generatePassword();
  await deps.volunteers.updatePasswordHash(volunteer.id, await hashPassword(temporaryPassword));
  await deps.volunteers.setStatus(volunteer.id, 'active');
  // The account is already activated with fresh credentials; a failed welcome
  // email must NOT fail the approval (that would leave the volunteer active with
  // a confusing 500). Log it so it is known the credentials weren't delivered —
  // the volunteer can recover them via "forgot password".
  try {
    await deps.notifier.notifyRegistrationApproved({
      email: volunteer.email,
      fullName: volunteer.fullName,
      temporaryPassword,
    });
  } catch {
    logger.warn('approval welcome email failed (volunteer activated; use password reset)', {
      volunteerId: volunteer.id,
    });
  }
  await deps.audit.append({
    userId: actor.id,
    role: actor.role,
    affectedRecordId: volunteer.id,
    actionType: 'volunteer_approved',
  });
}

/**
 * A coordinator or admin deactivates/suspends a volunteer (RF-2.3.2: `Inactivo`).
 * Bumps the token version so any active sessions are invalidated immediately
 * (ADR-0005).
 */
export async function rejectVolunteer(
  volunteerId: string,
  actor: Actor,
  deps: ManageVolunteerDeps,
): Promise<void> {
  const volunteer = await requireVolunteer(deps, volunteerId);
  await deps.volunteers.setStatus(volunteer.id, 'inactive');
  await deps.volunteers.bumpTokenVersion(volunteer.id);
  await deps.audit.append({
    userId: actor.id,
    role: actor.role,
    affectedRecordId: volunteer.id,
    actionType: 'volunteer_rejected',
  });
}
