import { ApiError } from '../../shared/errors/api-error';
import { generatePassword, hashPassword } from '../../shared/security/password';
import type { AuditLogRepository } from '../../domain/audit/audit';
import type { Volunteer, VolunteerRepository } from '../../domain/volunteer/volunteer';
import type { Notifier } from './ports';

export interface ManageVolunteerDeps {
  volunteers: VolunteerRepository;
  audit: AuditLogRepository;
  notifier: Notifier;
}

async function requireVolunteer(
  deps: ManageVolunteerDeps,
  volunteerId: string,
): Promise<Volunteer> {
  const volunteer = await deps.volunteers.findById(volunteerId);
  if (!volunteer) {
    throw new ApiError(404, 'NOT_FOUND', 'Volunteer not found');
  }
  return volunteer;
}

/**
 * Admin resolves an exception case: approve a pending volunteer. Because the
 * password is autogenerated (RF-2.2.4) and a pending volunteer never received
 * one, approval reissues fresh credentials and emails the welcome message so the
 * account is usable — otherwise the volunteer would be locked out.
 */
export async function approveVolunteer(
  volunteerId: string,
  adminId: string,
  deps: ManageVolunteerDeps,
): Promise<void> {
  const volunteer = await requireVolunteer(deps, volunteerId);
  const temporaryPassword = generatePassword();
  await deps.volunteers.updatePasswordHash(volunteer.id, await hashPassword(temporaryPassword));
  await deps.volunteers.setStatus(volunteer.id, 'active');
  await deps.notifier.notifyRegistrationApproved({
    email: volunteer.email,
    fullName: volunteer.fullName,
    temporaryPassword,
  });
  await deps.audit.append({
    userId: adminId,
    role: 'admin',
    affectedRecordId: volunteer.id,
    actionType: 'volunteer_approved',
  });
}

/**
 * Admin deactivates/rejects a volunteer. Bumps the token version so any active
 * sessions are invalidated immediately (ADR-0005).
 */
export async function rejectVolunteer(
  volunteerId: string,
  adminId: string,
  deps: ManageVolunteerDeps,
): Promise<void> {
  const volunteer = await requireVolunteer(deps, volunteerId);
  await deps.volunteers.setStatus(volunteer.id, 'inactive');
  await deps.volunteers.bumpTokenVersion(volunteer.id);
  await deps.audit.append({
    userId: adminId,
    role: 'admin',
    affectedRecordId: volunteer.id,
    actionType: 'volunteer_rejected',
  });
}
