/**
 * External-service ports for the volunteer feature (Adapter pattern). Concrete
 * adapters live in infrastructure; the use cases depend only on these interfaces.
 */

export interface FpvVerificationInput {
  /** FPV registration number (`numero_fpv`); the `fpv` query param of the API. */
  professionalId: string;
  /** National ID / cédula (`numero_documento`); the `national_id` query param. */
  nationalId: string;
  fullName: string;
}

export interface FpvVerificationResult {
  valid: boolean;
  reason?: string;
}

/**
 * Point-in-time verifier against the FPV registry. The real HTTP contract is not
 * defined yet, so the default implementation is a documented dummy that always
 * approves; swap it via config when the contract exists (see ADR-0013).
 */
export interface FpvVerifier {
  verify(input: FpvVerificationInput): Promise<FpvVerificationResult>;
}

export interface RegistrationNotification {
  email?: string;
  fullName: string;
  /**
   * Temporary autogenerated password (RF-2.2.4) included in the welcome email
   * of an activated volunteer. Present only on the approved path. Never logged.
   */
  temporaryPassword?: string;
}

/** Notification for a coordinator invitation (RF-2.6). */
export interface InvitationNotification {
  email: string;
  fullName: string;
  /** Public link the invitee opens to set their password and activate. */
  acceptUrl: string;
  /** When the invitation stops being valid. */
  expiresAt: Date;
}

/** Notification for a password reset request (RF-2.2.4, issue #36). */
export interface PasswordResetNotification {
  email: string;
  fullName: string;
  /** Public link the volunteer opens to set a new password; carries the token. */
  resetUrl: string;
  /** When the reset link stops being valid. */
  expiresAt: Date;
}

/** Sends volunteer registration notifications (Adapter; LogNotifier or SmtpNotifier). */
export interface Notifier {
  notifyRegistrationApproved(notification: RegistrationNotification): Promise<void>;
  notifyRegistrationPending(notification: RegistrationNotification): Promise<void>;
  /** Emails a coordinator the invitation link to complete their sign-up (RF-2.6). */
  notifyCoordinatorInvitation(notification: InvitationNotification): Promise<void>;
  /** Emails a volunteer a one-time link to reset their password (RF-2.2.4). */
  notifyPasswordReset(notification: PasswordResetNotification): Promise<void>;
}
