import { randomUUID } from 'node:crypto';
import type { Hono } from 'hono';
import { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

/**
 * End-to-end volunteer registration / login / admin flow against the local
 * Supabase DB (Docker). Skipped when no DB is reachable.
 */
const DB_URL =
  process.env.TEST_DATABASE_URL ?? 'postgresql://postgres:postgres@127.0.0.1:54322/postgres';
const SUPABASE_URL = process.env.SUPABASE_URL ?? 'http://127.0.0.1:54321';
const SERVICE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ??
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU';

async function canConnect(): Promise<boolean> {
  const probe = new Client({ connectionString: DB_URL, connectionTimeoutMillis: 1500 });
  try {
    await probe.connect();
    await probe.end();
    return true;
  } catch {
    return false;
  }
}

const dbAvailable = await canConnect();

describe.skipIf(!dbAvailable)('volunteer registration & auth (e2e)', () => {
  let app: Hono;
  let pg: Client;
  let signToken: typeof import('../../src/shared/security/jwt').signToken;
  let consentVersion: string;
  const emails: string[] = [];

  beforeAll(async () => {
    process.env.SUPABASE_URL = SUPABASE_URL;
    process.env.SUPABASE_SERVICE_ROLE_KEY = SERVICE_KEY;
    process.env.PSEUDONYMIZATION_SALT ??= 'e2e-test-salt';
    process.env.JWT_SECRET ??= 'test-secret-value-at-least-32-bytes-long!!';
    app = (await import('../../api/index')).default;
    signToken = (await import('../../src/shared/security/jwt')).signToken;
    const consentRes = await app.request('/api/v1/consent/active');
    consentVersion = ((await consentRes.json()) as { version: string }).version;
    pg = new Client({ connectionString: DB_URL });
    await pg.connect();
  });

  afterAll(async () => {
    if (!pg) return;
    if (emails.length) {
      await pg.query('delete from volunteers where email = any($1)', [emails]);
    }
    await pg.end();
  });

  function post(path: string, body: unknown, headers: Record<string, string> = {}) {
    return app.request(path, {
      method: 'POST',
      body: JSON.stringify(body),
      headers: { 'Content-Type': 'application/json', ...headers },
    });
  }

  async function register(email: string, overrides: Record<string, unknown> = {}) {
    emails.push(email);
    return post('/api/v1/volunteers/register', {
      nombre: 'Ana Test',
      tipo_documento: 'V',
      numero_documento: `${randomUUID().slice(0, 8)}`,
      numero_fpv: `FPV-${randomUUID().slice(0, 8)}`,
      email,
      telefono: '04140000000',
      universidad: 'UCV',
      anio_egreso: 2015,
      colegio: 'Colegio de Psicólogos de Miranda',
      especialidad: 'clinica',
      modalidad: ['presencial', 'distancia'],
      disponibilidad_horaria: [{ dia: 'lunes', bloque: 'manana' }],
      // PAP declared so the rule cédula+FPV ∧ PAP=Sí activates the account.
      pap: true,
      pap_detalle: 'Curso PAP 2024',
      consentimiento: true,
      consentimiento_version: consentVersion,
      ...overrides,
    });
  }

  it('registers a volunteer as active and records consent (dummy FPV verifier approves)', async () => {
    const email = `vol-${randomUUID().slice(0, 8)}@example.com`;
    const res = await register(email);
    expect(res.status).toBe(202);
    const body = (await res.json()) as { voluntario_id: string; estado_validacion: string };
    expect(body.estado_validacion).toBe('validado');

    const row = await pg.query(
      `select status, password_hash, consent_version, consent_accepted_at,
              document_type, document_number, university, graduation_year,
              colegio, modalities, availability_schedule, pap_trained
       from volunteers where id = $1`,
      [body.voluntario_id],
    );
    expect(row.rows[0]?.status).toBe('active');
    expect(row.rows[0]?.consent_version).toBe(consentVersion);
    expect(row.rows[0]?.consent_accepted_at).not.toBeNull();
    // Password is autogenerated server-side (none sent in the request) and stored
    // only as an argon2 hash (RF-2.2.4).
    expect(row.rows[0]?.password_hash).toMatch(/^\$argon2id\$/);
    // Full applicant profile persisted (RF-2.1.2).
    expect(row.rows[0]?.document_type).toBe('V');
    expect(row.rows[0]?.university).toBe('UCV');
    expect(row.rows[0]?.graduation_year).toBe(2015);
    expect(row.rows[0]?.modalities).toEqual(['presencial', 'distancia']);
    expect(row.rows[0]?.availability_schedule).toEqual([{ dia: 'lunes', bloque: 'manana' }]);
    expect(row.rows[0]?.pap_trained).toBe(true);

    const audit = await pg.query(
      'select 1 from audit_log where affected_record_id = $1 and action_type = $2',
      [body.voluntario_id, `consent_accepted:${consentVersion}`],
    );
    expect(audit.rowCount).toBe(1);
  });

  it('rejects registration without informed consent (RF-2.1.1)', async () => {
    const email = `noconsent-${randomUUID().slice(0, 8)}@example.com`;
    const res = await register(email, { consentimiento: false });
    expect(res.status).toBe(400);
  });

  it('rejects registration with a stale consent version', async () => {
    const email = `stale-${randomUUID().slice(0, 8)}@example.com`;
    const res = await register(email, { consentimiento_version: 'v0.0.0-old' });
    expect(res.status).toBe(409);
  });

  it('requires PAP detail when PAP training is declared (RF-2.1.2)', async () => {
    const email = `pap-${randomUUID().slice(0, 8)}@example.com`;
    const res = await register(email, { pap_detalle: undefined });
    expect(res.status).toBe(400);
  });

  it('stays pending when PAP is not declared even though FPV approves (RF-2.2)', async () => {
    const email = `nopap-${randomUUID().slice(0, 8)}@example.com`;
    const res = await register(email, { pap: false });
    expect(res.status).toBe(202);
    const body = (await res.json()) as { voluntario_id: string; estado_validacion: string };
    expect(body.estado_validacion).toBe('pendiente');
    const row = await pg.query('select status from volunteers where id = $1', [body.voluntario_id]);
    expect(row.rows[0]?.status).toBe('pending_approval');
  });

  it('logs in with the stored credentials and rejects a wrong password', async () => {
    // The password is autogenerated and only emailed, so seed a known hash to
    // exercise login deterministically.
    const { hashPassword } = await import('../../src/shared/security/password');
    const email = `login-${randomUUID().slice(0, 8)}@example.com`;
    emails.push(email);
    const passwordHash = await hashPassword('known-test-password');
    await pg.query(
      `insert into volunteers (full_name, professional_id, email, role, password_hash, status)
       values ('Login', $1, $2, 'psychologist', $3, 'active')`,
      [`FPV-${randomUUID().slice(0, 8)}`, email, passwordHash],
    );

    const ok = await post('/api/v1/auth/login', { email, contrasena: 'known-test-password' });
    expect(ok.status).toBe(200);
    expect((await ok.json() as { token: string }).token).toBeTruthy();

    const bad = await post('/api/v1/auth/login', { email, contrasena: 'wrong-password' });
    expect(bad.status).toBe(401);
  });

  it('lets an admin approve a pending volunteer and reject another', async () => {
    const adminToken = await signToken(
      { sub: randomUUID(), role: 'admin', tokenVersion: 1 },
      { ttlSeconds: 300, type: 'access' },
    );
    const auth = { Authorization: `Bearer ${adminToken}` };

    // Seed a pending volunteer directly.
    const email = `pending-${randomUUID().slice(0, 8)}@example.com`;
    emails.push(email);
    const seeded = await pg.query<{ id: string }>(
      `insert into volunteers (full_name, professional_id, email, role, password_hash, status)
       values ('Pending', $1, $2, 'psychologist', 'x', 'pending_approval') returning id`,
      [`FPV-${randomUUID().slice(0, 8)}`, email],
    );
    const id = seeded.rows[0]!.id;

    const approve = await post(`/api/v1/volunteers/${id}/approve`, {}, auth);
    expect(approve.status).toBe(200);
    const afterApprove = await pg.query('select status from volunteers where id = $1', [id]);
    expect(afterApprove.rows[0]?.status).toBe('active');

    const reject = await post(`/api/v1/volunteers/${id}/reject`, {}, auth);
    expect(reject.status).toBe(200);
    const afterReject = await pg.query('select status, token_version from volunteers where id = $1', [
      id,
    ]);
    expect(afterReject.rows[0]?.status).toBe('inactive');
    expect(afterReject.rows[0]?.token_version).toBe(2);
  });

  it('rejects admin endpoints without an admin token', async () => {
    const res = await app.request('/api/v1/volunteers', { method: 'GET' });
    expect(res.status).toBe(401);
  });
});
