import { createTransport, type Transporter } from 'nodemailer';
import type { AppConfig } from '../../config';
import type {
  InvitationNotification,
  Notifier,
  PasswordResetNotification,
  RegistrationNotification,
} from '../../application/volunteer/ports';
import { logger } from '../../shared/logger';
import {
  buildInvitationEmail,
  buildPasswordResetEmail,
  buildPendingEmail,
  buildWelcomeEmail,
} from './welcome-email';

/**
 * Real volunteer notifier over SMTP (RF-2.2.4) using nodemailer. The welcome
 * email carries the temporary autogenerated password; the password is only ever
 * placed in the email body — it is never logged. Host/port/from come from config
 * and the SMTP password (if any) from the SMTP_PASSWORD env var.
 *
 * In local dev, point this at the Supabase Inbucket SMTP server and read the
 * emails at http://localhost:54324.
 */
export class SmtpNotifier implements Notifier {
  private readonly transporter: Transporter;
  private readonly from: string;
  private readonly loginUrl: string;

  constructor(config: AppConfig['email']) {
    this.loginUrl = config.login_url;
    // SMTP account settings may be overridden by env so real credentials (and the
    // sender identity, which some providers like Gmail must match the account)
    // never live in the repo. Falls back to config (`email.smtp` / `email.from`).
    this.from = process.env.SMTP_FROM || config.from;
    const host = process.env.SMTP_HOST || config.smtp.host;
    const port = process.env.SMTP_PORT ? Number(process.env.SMTP_PORT) : config.smtp.port;
    const username = process.env.SMTP_USERNAME || config.smtp.username;
    const password = process.env.SMTP_PASSWORD;
    this.transporter = createTransport({
      host,
      port,
      // Port 465 uses implicit TLS (SSL); 587/2525 use STARTTLS (secure: false).
      // Works with any provider (Gmail, Brevo, SendGrid, Mailtrap, Resend…) by
      // just changing host/port/credentials.
      secure: port === 465,
      auth: username && password ? { user: username, pass: password } : undefined,
    });
  }

  async notifyRegistrationApproved(notification: RegistrationNotification): Promise<void> {
    if (!notification.email) return;
    const { subject, text, html } = buildWelcomeEmail(notification, this.loginUrl);
    await this.transporter.sendMail({ from: this.from, to: notification.email, subject, text, html });
    // Log the event WITHOUT the password (logger also redacts email).
    logger.info('volunteer welcome email sent', { email: notification.email, withCredentials: true });
  }

  async notifyRegistrationPending(notification: RegistrationNotification): Promise<void> {
    if (!notification.email) return;
    const { subject, text, html } = buildPendingEmail(notification);
    await this.transporter.sendMail({ from: this.from, to: notification.email, subject, text, html });
    logger.info('volunteer pending email sent', { email: notification.email });
  }

  async notifyCoordinatorInvitation(notification: InvitationNotification): Promise<void> {
    const { subject, text, html } = buildInvitationEmail(notification);
    await this.transporter.sendMail({ from: this.from, to: notification.email, subject, text, html });
    // Log WITHOUT the acceptUrl (it carries the raw token); logger redacts email.
    logger.info('coordinator invitation email sent', { email: notification.email });
  }

  async notifyPasswordReset(notification: PasswordResetNotification): Promise<void> {
    const { subject, text, html } = buildPasswordResetEmail(notification);
    await this.transporter.sendMail({ from: this.from, to: notification.email, subject, text, html });
    // Log WITHOUT the resetUrl (it carries the raw token); logger redacts email.
    logger.info('password reset email sent', { email: notification.email });
  }
}
