import type { InvitationNotification, RegistrationNotification } from '../../application/volunteer/ports';

export interface WelcomeEmail {
  subject: string;
  body: string;
}

/**
 * Renders the Spanish welcome email for an activated volunteer (RF-2.2.4),
 * including the temporary autogenerated password and the sign-in URL. Kept as a
 * pure function so it can be reused/tested independently of the transport.
 */
export function buildWelcomeEmail(
  notification: RegistrationNotification,
  loginUrl: string,
): WelcomeEmail {
  return {
    subject: 'Bienvenido/a a Sostén — credenciales de acceso',
    body: [
      `Hola ${notification.fullName},`,
      '',
      'Tu registro como psicólogo voluntario fue validado. Ya puedes iniciar sesión:',
      '',
      `  Acceso: ${loginUrl}`,
      `  Usuario: ${notification.email ?? '(tu correo)'}`,
      `  Contraseña temporal: ${notification.temporaryPassword ?? ''}`,
      '',
      'Por seguridad, te recomendamos cambiarla en cuanto esté disponible esa opción.',
      '',
      'Federación de Psicólogos de Venezuela · Sostén',
    ].join('\n'),
  };
}

/** Pending-review email (no credentials yet). */
export function buildPendingEmail(notification: RegistrationNotification): WelcomeEmail {
  return {
    subject: 'Sostén — tu registro está en revisión',
    body: [
      `Hola ${notification.fullName},`,
      '',
      'Recibimos tu registro como psicólogo voluntario. Está en revisión por la FPV;',
      'te enviaremos tus credenciales de acceso en cuanto sea aprobado.',
      '',
      'Federación de Psicólogos de Venezuela · Sostén',
    ].join('\n'),
  };
}

/**
 * Renders the coordinator invitation email (RF-2.6): a one-time link to set the
 * password and activate the account, with the expiry date. The link carries the
 * raw token; it is never logged.
 */
export function buildInvitationEmail(notification: InvitationNotification): WelcomeEmail {
  return {
    subject: 'Sostén — invitación para coordinar',
    body: [
      `Hola ${notification.fullName},`,
      '',
      'Has sido invitado/a a unirte a Sostén como coordinador/a de la FPV.',
      'Abre el siguiente enlace para definir tu contraseña y activar tu cuenta:',
      '',
      `  ${notification.acceptUrl}`,
      '',
      `La invitación vence el ${notification.expiresAt.toLocaleString('es-VE')}.`,
      '',
      'Si no esperabas esta invitación, puedes ignorar este mensaje.',
      '',
      'Federación de Psicólogos de Venezuela · Sostén',
    ].join('\n'),
  };
}
