import type {
  InvitationNotification,
  PasswordResetNotification,
  RegistrationNotification,
} from '../../application/volunteer/ports';
import { renderHtml, renderText, type EmailContent } from './email-template';

export interface WelcomeEmail {
  subject: string;
  /** Plain-text version (fallback + accessibility). */
  text: string;
  /** Branded HTML version. */
  html: string;
}

/** Assembles a {@link WelcomeEmail} (subject + text + html) from a content model. */
function build(subject: string, content: EmailContent): WelcomeEmail {
  return { subject, text: renderText(content), html: renderHtml(content) };
}

/**
 * Renders the Spanish welcome email for an activated volunteer (RF-2.2.4),
 * including the temporary autogenerated password and the sign-in URL. Kept as a
 * pure function so it can be reused/tested independently of the transport.
 */
export function buildWelcomeEmail(
  notification: RegistrationNotification,
  loginUrl: string,
): WelcomeEmail {
  return build('Bienvenido/a a PPV — credenciales de acceso', {
    preheader: 'Tu registro fue validado. Aquí están tus credenciales de acceso.',
    title: 'Tu acceso está listo',
    greeting: `Hola ${notification.fullName},`,
    paragraphs: [
      'Tu registro como psicólogo voluntario fue validado. Ya puedes iniciar sesión con estas credenciales:',
    ],
    infoRows: [
      { label: 'Usuario', value: notification.email ?? '(tu correo)' },
      { label: 'Contraseña temporal', value: notification.temporaryPassword ?? '', mono: true },
    ],
    button: { label: 'Iniciar sesión', url: loginUrl },
    afterParagraphs: [
      'Por seguridad, te recomendamos cambiarla en cuanto esté disponible esa opción.',
    ],
  });
}

/** Pending-review email (no credentials yet). */
export function buildPendingEmail(notification: RegistrationNotification): WelcomeEmail {
  return build('PPV — tu registro está en revisión', {
    preheader: 'Recibimos tu registro; está en revisión por la FPV.',
    title: 'Tu registro está en revisión',
    greeting: `Hola ${notification.fullName},`,
    paragraphs: [
      'Recibimos tu registro como psicólogo voluntario. Está en revisión por la FPV; te enviaremos tus credenciales de acceso en cuanto sea aprobado.',
    ],
  });
}

/**
 * Renders the coordinator invitation email (RF-2.6): a one-time link to set the
 * password and activate the account, with the expiry date. The link carries the
 * raw token; it is never logged.
 */
export function buildInvitationEmail(notification: InvitationNotification): WelcomeEmail {
  return build('PPV — invitación para coordinar', {
    preheader: 'Has sido invitado/a a coordinar en PPV. Activa tu cuenta.',
    title: 'Invitación para coordinar',
    greeting: `Hola ${notification.fullName},`,
    paragraphs: [
      'Has sido invitado/a a unirte a PPV como coordinador/a de la FPV. Abre el botón para definir tu contraseña y activar tu cuenta:',
    ],
    button: { label: 'Activar mi cuenta', url: notification.acceptUrl },
    afterParagraphs: [`La invitación vence el ${notification.expiresAt.toLocaleString('es-VE')}.`],
    note: 'Si no esperabas esta invitación, puedes ignorar este mensaje.',
  });
}

/**
 * Renders the password reset email (RF-2.2.4): a one-time link to set a new
 * password, with the expiry. The link carries the raw token; it is never logged.
 */
export function buildPasswordResetEmail(notification: PasswordResetNotification): WelcomeEmail {
  return build('PPV — recuperación de contraseña', {
    preheader: 'Solicitaste restablecer tu contraseña de PPV.',
    title: 'Recuperación de contraseña',
    greeting: `Hola ${notification.fullName},`,
    paragraphs: [
      'Recibimos una solicitud para restablecer tu contraseña de PPV. Abre el botón para definir una nueva:',
    ],
    button: { label: 'Restablecer contraseña', url: notification.resetUrl },
    afterParagraphs: [`El enlace vence el ${notification.expiresAt.toLocaleString('es-VE')}.`],
    note: 'Si no solicitaste este cambio, puedes ignorar este mensaje: tu contraseña actual seguirá siendo válida.',
  });
}
